# 开发环境配置文件

server:
  port: 8081     # Springboot占用端口

spring:
  datasource:
    publicKey: MFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBALCGIaSYvvVhBQHtERoH0yooMwMHJAjYIk0xJukt4vhNRHn11trwOP3JNECIm61xwd+5WlKw1877FtfiAdV02HMCAwEAAQ==
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver     # 数据库驱动
      url: jdbc:mysql://sh-cynosdbmysql-grp-le448ahi.sql.tencentcdb.com:20150/h5?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false     # 数据库链接
      username: root     # 数据库账号
      password: fjbNWA/mOMdBZNNWPAC18PKybq8p+/bo3X+0IsAN5X/AEF4CPjNm+oKFN9Fo12TlfL7yTzO6drApYTp1iikVKQ==    # 数据库密码
      connectionProperties: config.decrypt=true;config.decrypt.key=${spring.datasource.publicKey}
      filter:
        config:
          enabled: true



  devtools:
    restart:
      enabled: true     # 开启热更新