# 基础配置文件
spring:
  thymeleaf:
    cache: false
  profiles:
    active: dev     # 配置文件环境
  http:
    encoding:
      force: true
      charset: utf-8
      enabled: true
  mvc:
    static-path-pattern: /static/**
    throw-exception-if-no-handler-found: true     # 接口404时抛出异常
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: auto


server:
  tomcat:
    uri-encoding: UTF-8
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
       id-type: auto